# Generated by Django 4.2.7 on 2026-07-23 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='capturedimage',
            name='is_exported',
            field=models.BooleanField(default=False, help_text='Whether the image has been exported to the PC folder'),
        ),
    ]
