# Generated by Django 4.2.7 on 2026-08-12 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_last_seen'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('documentation', 'Documentation'), ('video_tutorial', 'Video Tutorial'), ('faq', 'FAQ')], max_length=50, unique=True)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('content', models.TextField(blank=True, default='')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='tutorials/')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='help_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Help Content',
                'db_table': 'help_content',
            },
        ),
    ]
