# Generated by Django 4.2.7 on 2026-08-13 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_helpcontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capturedimage',
            name='image_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
